export type RuntimeType = 'string' | 'number' | 'boolean' | 'null' | 'File' | 'FormData' | 'object' | 'array'
export type RequestSource = 'body' | 'query' | 'params' | 'multipart'
export interface ContractField { admin: string; server: string; type: RuntimeType; required: boolean; nullable?: boolean; notes?: string }
export interface AdminServerContract { dialog: string; operation: 'create' | 'update' | 'upload' | 'status'; method: 'POST' | 'PATCH' | 'PUT' | 'DELETE'; path: string; source: RequestSource; serverValidator: string | null; fields: ContractField[]; knownMismatches?: string[] }

export const adminServerContracts: AdminServerContract[] = [
  { dialog: 'UserFormDialog', operation: 'create', method: 'POST', path: '/admin/users', source: 'body', serverValidator: 'user.createUserSchema', fields: [
    { admin: 'email', server: 'email', type: 'string', required: true }, { admin: 'password', server: 'password', type: 'string', required: true }, { admin: 'fullName', server: 'fullName', type: 'string', required: true, notes: 'Admin max 100 vs Server max 255' }, { admin: 'phone', server: 'phone', type: 'string', required: false, nullable: true }, { admin: 'roleCode', server: 'roleCode', type: 'string', required: false }], knownMismatches: ['Role enum differs; fullName length differs'] },
  { dialog: 'NewsFormDialog', operation: 'create', method: 'POST', path: '/admin/cms/news', source: 'multipart', serverValidator: 'cms.newsCreateSchema', fields: [
    { admin: 'title', server: 'title', type: 'string', required: true }, { admin: 'content', server: 'content', type: 'string', required: true }, { admin: 'summary', server: 'summary', type: 'string', required: false, nullable: true }, { admin: 'slug', server: 'slug', type: 'string', required: false, notes: 'Not present in current Server schema' }, { admin: 'thumbnail_url', server: 'cover', type: 'File', required: false }], knownMismatches: ['Legacy is_published/is_featured/tags fields are not in newsCreateSchema'] },
  { dialog: 'DocumentFormDialog', operation: 'create', method: 'POST', path: '/admin/cms/documents', source: 'multipart', serverValidator: 'cms.documentCreateSchema', fields: [
    { admin: 'title', server: 'title', type: 'string', required: true }, { admin: 'documentCode', server: 'documentCode', type: 'string', required: true }, { admin: 'issuingAgency', server: 'issuingAgency', type: 'string', required: true }, { admin: 'issuedAt', server: 'issuedAt', type: 'string', required: false, nullable: true }, { admin: 'file', server: 'fileObjectId', type: 'File', required: true, notes: 'Upload must resolve to numeric object ID' }] },
  { dialog: 'MapImageFormDialog', operation: 'create', method: 'POST', path: '/admin/cms/pdf-maps', source: 'multipart', serverValidator: 'cms.pdfMapCreateSchema', fields: [
    { admin: 'title', server: 'title', type: 'string', required: true }, { admin: 'scaleLabel', server: 'scaleLabel', type: 'string', required: true }, { admin: 'mapYear', server: 'mapYear', type: 'number', required: true }, { admin: 'preparingAgency', server: 'preparingAgency', type: 'string', required: true }, { admin: 'file', server: 'fileObjectId', type: 'File', required: true }] },
  { dialog: 'MapLayerFormDialog', operation: 'update', method: 'PATCH', path: '/admin/layers/:layerId', source: 'body', serverValidator: 'layer.layerUpdateSchema', fields: [
    { admin: 'expectedUpdatedAt', server: 'expectedUpdatedAt', type: 'string', required: true }, { admin: 'name_vi', server: 'nameVi', type: 'string', required: false }, { admin: 'category_name', server: 'categoryName', type: 'string', required: false, nullable: true }, { admin: 'is_public', server: 'isPublic', type: 'boolean', required: false }, { admin: 'is_enable_default', server: 'isEnableDefault', type: 'boolean', required: false }], knownMismatches: ['Dialog emits snake_case while Server layerUpdateSchema expects camelCase'] },
  { dialog: 'KttvScenarioFormDialog', operation: 'create', method: 'POST', path: '/admin/flood/scenarios', source: 'body', serverValidator: 'flood.createScenarioSchema', fields: [
    { admin: 'code', server: 'code', type: 'string', required: true }, { admin: 'nameVi', server: 'nameVi', type: 'string', required: true }, { admin: 'layerCode', server: 'layerCode', type: 'string', required: true }, { admin: 'minRainfall', server: 'minRainfall', type: 'number', required: false, nullable: true }, { admin: 'isActive', server: 'isActive', type: 'boolean', required: false }] },
  { dialog: 'MapLayerApiFormDialog', operation: 'create', method: 'POST', path: '/admin/api-registry', source: 'body', serverValidator: 'api-registry.registryBody', fields: [
    { admin: 'layer_id', server: 'layerId', type: 'number', required: true }, { admin: 'name', server: 'name', type: 'string', required: true }, { admin: 'metadata', server: 'readFields/writeFields/searchFields/allowedMethods/defaultSortField', type: 'object', required: true, notes: 'Service canonicalizes layer metadata into the registry body' }] },
  { dialog: 'FeedbackUpdateDialog', operation: 'status', method: 'PATCH', path: '/admin/field-reports/:id/review', source: 'body', serverValidator: 'field-report.reviewSchema', fields: [
    { admin: 'status', server: 'status', type: 'string', required: true }, { admin: 'rejection_reason', server: 'reason', type: 'string', required: false, nullable: true }, { admin: 'updated_at', server: 'expectedUpdatedAt', type: 'string', required: true }] },
  { dialog: 'GeoTiffUploadDialog', operation: 'upload', method: 'POST', path: '/admin/remote-sensing/images', source: 'multipart', serverValidator: 'remote-sensing.createSchema', fields: [
    { admin: 'title', server: 'title', type: 'string', required: true }, { admin: 'epsg', server: 'srid', type: 'number', required: true }, { admin: 'file', server: 'fileObjectId', type: 'File', required: true }], knownMismatches: ['Upload pipeline requires File to object ID mapping'] },
]
